### ISSUE TITLE
[Series] Deep learning ứng dụng (dl_ap) task List

### ISSUE THREAD

**Issue by gachiemchiep** [dlapplications/dlapplications.github.io#19]
# Task control cho series dl_ap. 

## Chú ý :
1. Task control only, không comment discussion trong này.
2. Khi cần thiết trực tiếp edit issue này để cập nhật tình hình hiện tại 

## All Task

- [ ] Comment và Discussion tại: https://github.com/dlapplications/dlapplications.github.io/issues/9
- [ ] Number plate recognition
    - [ ] Number plate region detection:  https://github.com/dlapplications/dlapplications.github.io/issues/13
    - [ ] Number plate recognition : LeNet + Mnist
    - [ ] Number plate recognition : LeNet + other dateset
   - [ ] Number plate recognition : OtherNetwork + other dateset

continue ....
